CROSS_COMPILE:= arm-hisiv100nptl-linux-
ARCH:= arm
CC:= $(CROSS_COMPILE)gcc
LD:= $(CROSS_COMPILE)ld

objects = p4storage.o \
		  p4storagefun.o common.o

p4storage:$(objects)
	$(CC) -o p4storage $(objects) -lpthread

clean:
	rm *~ $(objects) p4storage
	rm video/* -rf
	rm index/* -rf
